config/routes.rb
Rails.application.routes.draw do
  resources :npcs
  get 'characters/show'

  post 'characters/create'

  get 'characters/new'

  get 'characters/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :characters

  root 'characters#index'
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :race
  belongs_to :klass # TODO: Refactor to enum
  has_and_belongs_to_many :skills
	validates :name, presence: true,
		length: { minimum: 2 }
  validates :level, :exp, :strength, :agility, :intellect, :cunning, :willpower, :presence,
            :hitpoints, :stamina, :mana, :armor, :resistence, presence: true

  # TODO: Refactor to constructor
  def init
    initMods
    initSkills
  end

  # returns an Array of green and yellow dice count
  def calcDices(skill)
    green_count = self[skill.bound_attribute]
    yellow_count = 0
    level = CharactersSkills.where(character_id: self.id, skill_id: skill.id).first.level
    if level > 0
      while green_count >= 0 && level > 0 do
        green_count -= 1
        level -= 1
        yellow_count += 1
      end
    end
    [green_count, yellow_count]
  end

  private

  def initMods
    klass_mod = getInitKlassMod
    race_mod = getInitRaceMod

    # Resources
    self.hitpoints = 10 + (klass_mod[:hitpoints] || 0) + (race_mod[:hitpoints] || 0)
    self.stamina = 10 + (klass_mod[:stamina] || 0) + (race_mod[:stamina] || 0)
    self.mana = 0 + (klass_mod[:mana] || 0) + (race_mod[:mana] || 0)
    
    # Defense
    self.armor = 0
    self.resistence = 0 + (klass_mod[:resistence] || 0) + (race_mod[:resistence] || 0)

    # Attributes
    self.strength = 1 + (klass_mod[:strength] || 0) + (race_mod[:strength] || 0)
    self.agility = 1 + (klass_mod[:agility] || 0) + (race_mod[:agility] || 0)
    self.intellect = 1 + (klass_mod[:intellect] || 0) + (race_mod[:intellect] || 0)
    self.cunning = 1 + (klass_mod[:cunning] || 0) + (race_mod[:cunning] || 0)
    self.willpower = 1 + (klass_mod[:willpower] || 0) + (race_mod[:willpower] || 0)
    self.presence = 1 + (klass_mod[:presence] || 0) + (race_mod[:presence] || 0)
  end

  def initSkills
    self.skills << getInitCommonSkills
    self.skills << getInitKlassSkills
  end

  def getInitCommonSkills
    # common = 0
    Skill.where(skill_type: 0)
  end

  def getInitKlassSkills
    Skill.where(klass_id: klass.id)
  end

  # returns a hash of modifiers for an attribute
  # should return also Skills later
  # TODO: Documentate balancing for this mod
  # Mana classes get 10 Mana for free (like stamina)
  # 10 points total
  def getInitKlassMod
    # TODO: Refactor
    case klass.name
    when 'Krieger'
      return { hitpoints: 5, stamina: 3, strength: 1, agility: 1 }
    when 'Paladin'
      return { hitpoints: 3, stamina: 3, mana: 12, strength: 1, presence: 1 }
    when 'Jäger'
      return { hitpoints: 2, stamina: 4, mana: 12, agility: 1, intellect: 1 }
    when 'Schamane'
      return { hitpoints: 2, stamina: 3, mana: 13, agility: 1, intellect: 1 }
    when 'Druide'
      return { hitpoints: 3, stamina: 2, mana: 12, willpower: 1, presence: 1, resistence: 1 }
    when 'Schurke'
      return { hitpoints: 2, stamina: 6, agility: 1, cunning: 1 }
    when 'Hexenmeister'
      return { hitpoints: 1, mana: 16, intellect: 1, cunning: 1, resistence: 1 }
    when 'Magier'
      return { hitpoints: 0, mana: 17, intellect: 1, willpower: 1, resistence: 1 }
    when 'Priester'
      return { hitpoints: 0, mana: 17, willpower: 1, presence: 1, resistence: 1 }
    end
  end

  # returns a hash of modifiers for an attribute
  # should return also Skills later
  # TODO: Documentate balancing for this mod
  # 8 points total
  def getInitRaceMod
    # TODO: Refactor
    case race.name
    when 'Mensch'
      return { hitpoints: 3, stamina: 4, willpower: 1 }
    when 'Zwerg'
      return { hitpoints: 4, stamina: 3, strength: 1 }
    when 'Nachtelf'
      return { hitpoints: 3, stamina: 4, presence: 1 }
    when 'Gnom'
      return { hitpoints: 3, stamina: 4, intellect: 1 }
    when 'Ork'
      return { hitpoints: 4, stamina: 3, strength: 1 }
    when 'Troll'
      return { hitpoints: 3, stamina: 4, willpower: 1 }
    when 'Taure'
      return { hitpoints: 5, stamina: 3 }
    when 'Untoter'
      return { hitpoints: 3, stamina: 4, cunning: 1 }
    end 
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_create_params.merge({ level: 1 }))
    @character.init
    if @character.save
      redirect_to @character
    else
      render "new"
    end
  end

  def edit
  end

  # PATCH/PUT /npcs/1
  # PATCH/PUT /npcs/1.json
  def update
    respond_to do |format|
      if @character.update(character_update_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private
    def set_character
      @character = Character.find(params[:id])
    end

    def character_create_params
      params.require(:character).permit(:klass_id, :name, :race_id)
    end

    def character_update_params
      params.require(:character).permit()
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/create.html.erb
<h1>Characters#create</h1>
<p>Find me in app/views/characters/create.html.erb</p>

app/views/characters/edit.html.erb
<%= link_to 'Zurück', @character %>
<br><h1>Aufsteigen</h1>

<%= form_for @character, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
  <h1><%= @character.name %></h1>
  <br>Rasse: <%= @character.race.name %>
  <br>Klasse: <%= @character.klass.name %>
  <br>Level: <%= @character.level %> | Exp: <%= @character.exp %>
  <br>
  <br><h2>Ressourcen</h2>
  <br>Leben: <%= @character.hitpoints %>
  <br>Energie: <%= @character.stamina %>
  <br>Mana: <%= @character.mana %>
  <br><h2>Verteidigung</h2>
  <br>Rüstung: <%= @character.armor %>
  <br>Widerstand: <%= @character.resistence %>
  <br>
  <br><h2>Attribute</h2>
  <br>Stärke: <%= @character.strength %>
  <br>Beweglichkeit: <%= @character.agility %>
  <br>Intelligenz: <%= @character.intellect %>
  <br>Täuschung: <%= @character.cunning %>
  <br>Willenskraft: <%= @character.willpower %>
  <br>Ausstrahlung: <%= @character.presence %>
  <br>
  <br><h2>Fertigkeiten</h2>
  <% @character.skills.each do |skill| %>
    <%= skill.name %> | 
    <%= skill.skill_type.capitalize() %> | 
    <% dices = @character.calcDices skill %><br>
    <% dices[0].times do %> 
      <span style="color: green">◆</span>
    <% end %> |
    <% dices[1].times do %> 
      <span style="color: yellow">◆</span>
    <% end %>
  <% end %>
  <br><%= f.submit "Bestätigen" %>
<% end %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<% @characters = Character.all  %>

<%= link_to 'NPCs', npcs_path %>

<h1>Charaktere</h1>
<%= link_to 'Neu', new_character_path %>

<ul>
  <% @characters.each do |character| %>
    <li><%= link_to character.name, character %></li>
  <% end %>
</ul>

app/views/characters/new.html.erb
<h1>Charakter erstellen</h1>

<%= form_for @character, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
 	<label>Name: <%= f.text_field :name %></label>
  <br>Rasse: <%= f.collection_select :race_id, Race.order(:id),:id, :name %>
  <br>Klasse: <%= f.collection_select :klass_id, Klass.order(:id),:id, :name %>
  <br><%= f.submit "Erstellen" %>
<% end %>

app/views/characters/show.html.erb
<br><%= link_to 'Zurück', characters_path %>
<%= link_to 'Aufsteigen', edit_character_path(@character) %>
<h1><%= @character.name %></h1>
<br>Rasse: <%= @character.race.name %>
<br>Klasse: <%= @character.klass.name %>
<br>Level: <%= @character.level %> | Exp: <%= @character.exp %>
<br>
<br><h2>Ressourcen</h2>
<br>Leben: <%= @character.hitpoints %>
<br>Energie: <%= @character.stamina %>
<br>Mana: <%= @character.mana %>
<br><h2>Verteidigung</h2>
<br>Rüstung: <%= @character.armor %>
<br>Widerstand: <%= @character.resistence %>
<br>
<br><h2>Attribute</h2>
<br>Stärke: <%= @character.strength %>
<br>Beweglichkeit: <%= @character.agility %>
<br>Intelligenz: <%= @character.intellect %>
<br>Täuschung: <%= @character.cunning %>
<br>Willenskraft: <%= @character.willpower %>
<br>Ausstrahlung: <%= @character.presence %>
<br>
<br><h2>Fertigkeiten</h2>
<% @character.skills.each do |skill| %>
  <% dices = @character.calcDices skill %><br>
  <%= skill.name %> | 
  <%= skill.skill_type.capitalize() %> | 
  <% dices[0].times do %> 
    <span style="color: green">◆</span>
  <% end %> |
  <% dices[1].times do %> 
    <span style="color: yellow">◆</span>
  <% end %>
<% end %>