config/routes.rb
Rails.application.routes.draw do
  resources :npcs
  get 'characters/show'

  post 'characters/create'

  get 'characters/new'

  get 'characters/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :characters

  root 'characters#index'
end

app/models/npc.rb
class Npc < ApplicationRecord
  belongs_to :race, optional: true
  belongs_to :klass, optional: true # TODO: Refactor to enum
  has_and_belongs_to_many :skills
  validates :name, presence: true,
    length: { minimum: 2 }
  validates :level, :strength, :agility, :intellect, :cunning, :willpower, :presence,
            :hitpoints, :stamina, :mana, :armor, :resistence, presence: true
end

app/controllers/npcs_controller.rb
class NpcsController < ApplicationController
  before_action :set_npc, only: [:show, :edit, :update, :destroy]

  # GET /npcs
  # GET /npcs.json
  def index
    @npcs = Npc.all
  end

  # GET /npcs/1
  # GET /npcs/1.json
  def show
  end

  # GET /npcs/new
  def new
    @npc = Npc.new
  end

  # GET /npcs/1/edit
  def edit
  end

  # POST /npcs
  # POST /npcs.json
  def create
    @npc = Npc.new(npc_params)

    respond_to do |format|
      if @npc.save
        format.html { redirect_to @npc, notice: 'Npc was successfully created.' }
        format.json { render :show, status: :created, location: @npc }
      else
        format.html { render :new }
        format.json { render json: @npc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /npcs/1
  # PATCH/PUT /npcs/1.json
  def update
    respond_to do |format|
      if @npc.update(npc_params)
        format.html { redirect_to @npc, notice: 'Npc was successfully updated.' }
        format.json { render :show, status: :ok, location: @npc }
      else
        format.html { render :edit }
        format.json { render json: @npc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /npcs/1
  # DELETE /npcs/1.json
  def destroy
    @npc.destroy
    respond_to do |format|
      format.html { redirect_to npcs_url, notice: 'Npc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_npc
      @npc = Npc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def npc_params
      params.require(:npc).permit(:name, :level, :hitpoints, :stamina, :mana, :armor, :resistence, :strength, :agility, :intellect, :cunning, :willpower, :presence, :race_id, :klass_id, :notice)
    end
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/views/npcs/_form.html.erb
<%= form_with(model: npc, local: true) do |form| %>
  <% if npc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(npc.errors.count, "error") %> prohibited this npc from being saved:</h2>

      <ul>
      <% npc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% skills = Skill.all %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :npc_name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level, id: :npc_level %>
  </div>

  <div class="field">
    <%= form.label :hitpoints %>
    <%= form.number_field :hitpoints, id: :npc_hitpoints %>
  </div>

  <div class="field">
    <%= form.label :stamina %>
    <%= form.number_field :stamina, id: :npc_stamina %>
  </div>

  <div class="field">
    <%= form.label :mana %>
    <%= form.number_field :mana, id: :npc_mana %>
  </div>

  <div class="field">
    <%= form.label :armor %>
    <%= form.number_field :armor, id: :npc_armor %>
  </div>

  <div class="field">
    <%= form.label :resistence %>
    <%= form.number_field :resistence, id: :npc_resistence %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.number_field :strength, id: :npc_strength %>
  </div>

  <div class="field">
    <%= form.label :agility %>
    <%= form.number_field :agility, id: :npc_agility %>
  </div>

  <div class="field">
    <%= form.label :intellect %>
    <%= form.number_field :intellect, id: :npc_intellect %>
  </div>

  <div class="field">
    <%= form.label :cunning %>
    <%= form.number_field :cunning, id: :npc_cunning %>
  </div>

  <div class="field">
    <%= form.label :willpower %>
    <%= form.number_field :willpower, id: :npc_willpower %>
  </div>

  <div class="field">
    <%= form.label :presence %>
    <%= form.number_field :presence, id: :npc_presence %>
  </div>

  <div class="field">
    <%= form.label :race_id %>
    <%= form.number_field :race_id, id: :npc_race_id %>
  </div>

  <div class="field">
    <%= form.label :klass_id %>
    <%= form.number_field :klass_id, id: :npc_klass_id %>
  </div>

  <div class="field">
    <%= form.label :notice %>
    <%= form.text_area :notice, id: :npc_notice %>
  </div>

  <div class="field">
    <select multiple>
    <% skills.each do |skill| %>
      <option value='<%= skill.id %>'><%= skill.name %></option>
    <% end %>
    </select>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/npcs/edit.html.erb
<h1>Editing Npc</h1>

<%= render 'form', npc: @npc %>

<%= link_to 'Show', @npc %> |
<%= link_to 'Back', npcs_path %>

app/views/npcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Npcs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Rasse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @npcs.each do |npc| %>
      <tr>
        <td><%= link_to npc.name, npc %></td>
        <td><%= npc.level %></td>
        <td><%= npc.race_id || '?' %></td>
        <td><%= link_to 'Bearbeiten', edit_npc_path(npc) %></td>
        <td><%= link_to 'Exterminate!', npc, method: :delete, data: { confirm: 'You sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Npc', new_npc_path %>

app/views/npcs/new.html.erb
<h1>New Npc</h1>

<%= render 'form', npc: @npc %>

<%= link_to 'Back', npcs_path %>

app/views/npcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @npc.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @npc.level %>
</p>

<p>
  <strong>Hitpoints:</strong>
  <%= @npc.hitpoints %>
</p>

<p>
  <strong>Stamina:</strong>
  <%= @npc.stamina %>
</p>

<p>
  <strong>Mana:</strong>
  <%= @npc.mana %>
</p>

<p>
  <strong>Armor:</strong>
  <%= @npc.armor %>
</p>

<p>
  <strong>Resistence:</strong>
  <%= @npc.resistence %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @npc.strength %>
</p>

<p>
  <strong>Agility:</strong>
  <%= @npc.agility %>
</p>

<p>
  <strong>intellect:</strong>
  <%= @npc.intellect %>
</p>

<p>
  <strong>Cunning:</strong>
  <%= @npc.cunning %>
</p>

<p>
  <strong>Willpower:</strong>
  <%= @npc.willpower %>
</p>

<p>
  <strong>Presence:</strong>
  <%= @npc.presence %>
</p>

<p>
  <strong>Race:</strong>
  <%= @npc.race.name %>
</p>

<p>
  <strong>Klass:</strong>
  <%= @npc.klass && @npc.klass.name %>
</p>

<p>
  <strong>Notice:</strong>
  <%= @npc.notice %>
</p>

<%= link_to 'Edit', edit_npc_path(@npc) %> |
<%= link_to 'Back', npcs_path %>